spring:
  main.banner-mode: off

  mail:
    username: ${USERNAME:test@test.com}
    host: ${HOST:localhost}
    port: ${PORT:25}

  cloud.stream:
    bindings:
      receiveEmail-in-0:
        destination: mailer
    kafka:
      binder:
        brokers: ${KAFKA_HOST:localhost:9094}
      streams.binder:
        configuration:
          spring.json.use.type.headers: false
        functions:
          receiveEmail:
            applicationId: mailer